### ISSUE TITLE
can not load .so

### ISSUE THREAD

**Issue by pribadihcr** [AastaNV/TRT_object_detection#1]
Hi @AastaNV 

I got the following error:
OSError: lib/libflattenconcat.so: cannot open shared object file: No such file or directory

**Comment by mosheliv** [comment]
Did you do the sudo make install?

**Comment by pribadihcr** [comment]
sudo make install?. is there that command in readme?. I just run the main.py

**Comment by mosheliv** [comment]
Oopssorry my bad, its not that

**Comment by pribadihcr** [comment]
any hint?

**Comment by AastaNV** [comment]
The library is Nano only. Do you meet this error on Jetson Nano?

**Comment by pribadihcr** [comment]
oh, I run it in PC.

**Comment by AastaNV** [comment]
You can build one for desktop on your own.

$ {tensorrt}/samples/python/uff_ssd
$ mkdir build
$ cd build
$ cmake ../
$ make

Replace the libflattenconcat.so file.

**Comment by pribadihcr** [comment]
@AastaNV which github repo for {tensorrt}?

**Comment by pribadihcr** [comment]
oh sorry found it, in /usr/src/tensorrt

**Comment by pribadihcr** [comment]
Yes, it run now :), Thanks

**Comment by AastaNV** [comment]
Go to know this

**Comment by SaddamBInSyed** [comment]
> The library is Nano only. Do you meet this error on Jetson Nano?

yes. I am trying to run the same on nano board and i face this error.
