### ISSUE TITLE
how to rebuild 'libflattenconcat.so ' on ubuntu

### ISSUE THREAD

**Issue by Programmerwyl** [AastaNV/TRT_object_detection#11]
When I compiled 'libflattenconcat.so' on ubuntu, it reported an error
I follow the process below：
$ {tensorrt}/samples/python/uff_ssd
$ mkdir build
$ cd build
$ cmake ../
$ make
I also try sudo to build it ,it still report errors

(base) wyl@wyl-Inspiron-3670:~/software/pc/TensorRT-6.0.1.5/samples/python/uff_ssd/build$ sudo cmake ../
-- The CXX compiler identification is GNU 7.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "10.1") 
-- Configurable variable TRT_LIB set to /usr/lib/x86_64-linux-gnu
-- Configurable variable TRT_INCLUDE set to /usr/include/x86_64-linux-gnu
-- Configurable variable CUDA_ROOT set to /usr/local/cuda

The following variables are derived from the values of the previous variables unless provided explicitly:

-- Configurable variable NVINFER_LIB set to _NVINFER_LIB-NOTFOUND
-- Configurable variable CUBLAS_LIB set to /usr/lib/x86_64-linux-gnu/libcublas.so
-- Configurable variable CUDA_INC_DIR set to /usr/local/cuda/include
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
_NVINFER_LIB
    linked by target "flattenconcat" in directory /home/wyl/software/pc/TensorRT-6.0.1.5/samples/python/uff_ssd

-- Configuring incomplete, errors occurred!
See also "/home/wyl/software/pc/TensorRT-6.0.1.5/samples/python/uff_ssd/build/CMakeFiles/CMakeOutput.log".

**Comment by Programmerwyl** [comment]
log files

[CMakeError.log](https://github.com/AastaNV/TRT_object_detection/files/3650079/CMakeError.log)

**Comment by Programmerwyl** [comment]
cmake  output log

[CMakeOutput.log](https://github.com/AastaNV/TRT_object_detection/files/3650082/CMakeOutput.log)

**Comment by Programmerwyl** [comment]
I have fixed it
firstly:
mkdir build
cd build
sudo cmake ..  -DNVINFER_LIB=/home/wyl/software/pc/TensorRT-6.0.1.5/lib/libnvinfer.so 

note: it is DNVINFER_LIB not  NVINFER_LIB

secondly:
 in /software/pc/TensorRT-6.0.1.5/samples/python/uff_ssd/plugin/FlattenConcat.cpp
Modify the path of the import  NvInferPlugin.h
#include "/home/wyl/software/pc/TensorRT-6.0.1.5/include/NvInferPlugin.h"

last: sudo make

**Comment by chiehpower** [comment]
very useful!! Thanks very much!!

**Comment by Yudachi-poi-poi** [comment]
Really helpful ! Thx
