### ISSUE TITLE
TRT_ssd_mobilenet_v2_coco_2018_03_29.bin used in Deepstream4.0

### ISSUE THREAD

**Issue by xinyuabcd** [AastaNV/TRT_object_detection#7]
Hello,
     I have built TRT_ssd_mobilenet_v2_coco_2018_03_29.bin successfully. However, when I use this file in the deepstream4.0, the error occurs  as follows:

deepstream-app: nvdsiplugin_ssd.cpp:72: FlattenConcat::FlattenConcat(const void*, size_t): Assertion `mConcatAxisID == 1 || mConcatAxisID == 2 || mConcatAxisID == 3' failed.
Aborted (core dumped)

**Comment by subzeromot** [comment]
I have this issue too, did you find how to fix it?
