### ISSUE TITLE
Unsupported operation Cast after re-training mobilenet v1/v2.

### ISSUE THREAD

**Issue by hosaka** [AastaNV/TRT_object_detection#8]
Hi @AastaNV ,

After re-training the mobilenet with a different dataset (i'm using egohands for hands detection) and reducing the number of classes from 90 to 1, I'm getting the following error

```
NOTE: UFF has been tested with TensorFlow 1.12.0. Other versions are not guaranteed to work
WARNING: The version of TensorFlow installed on this system is not guaranteed to work with UFF.
UFF Version 0.6.3
=== Automatically deduced input nodes ===
[name: "Input"
op: "Placeholder"
input: "Cast"
attr {
  key: "dtype"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "shape"
  value {
    shape {
      dim {
        size: 1
      }
      dim {
        size: 3
      }
      dim {
        size: 300
      }
      dim {
        size: 300
      }
    }
  }
}
]
=========================================

Using output node NMS
Converting to UFF graph
Warning: No conversion function registered for layer: NMS_TRT yet.
Converting NMS as custom op: NMS_TRT
WARNING:tensorflow:From /usr/lib/python3.6/dist-packages/uff/converters/tensorflow/converter.py:179: The name tf.AttrValue is deprecated. Please use tf.compat.v1.AttrValue instead.

Warning: No conversion function registered for layer: FlattenConcat_TRT yet.
Converting concat_box_conf as custom op: FlattenConcat_TRT
Warning: No conversion function registered for layer: Cast yet.
Converting Cast as custom op: Cast
Warning: No conversion function registered for layer: GridAnchor_TRT yet.
Converting GridAnchor as custom op: GridAnchor_TRT
Warning: No conversion function registered for layer: FlattenConcat_TRT yet.
Converting concat_box_loc as custom op: FlattenConcat_TRT
No. nodes: 451
UFF Output written to tmp.uff
[TensorRT] ERROR: UffParser: Validator error: Cast: Unsupported operation _Cast
[TensorRT] ERROR: Network must have at least one output
Traceback (most recent call last):
  File "main.py", line 44, in <module>
    buf = engine.serialize()
AttributeError: 'NoneType' object has no attribute 'serialize'
```

Comparing to the default model, the Placeholder layer has an additional "Cast" input layer, which is not supported by TensorRT. I'm trying to figure out how to use the graphsurgeon to handle this. Could you please propose any suggestions?

**Comment by hosaka** [comment]
I looked more carefully through the generated frozen graphs with tensorboard and found that ToFloat layer got replaced with the Cast layer during my training, perhaps due to the newer version of TF. I simply replaced ToFloat with Cast in the namespace_plugin_map and this worked.

However i'm having another issue now during UFF parsing:
```
=== Automatically deduced input nodes ===
[name: "Input"
op: "Placeholder"
attr {
  key: "dtype"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "shape"
  value {
    shape {
      dim {
        size: 1
      }
      dim {
        size: 3
      }
      dim {
        size: 300
      }
      dim {
        size: 300
      }
    }
  }
}
]
=========================================

Using output node NMS
Converting to UFF graph
Warning: No conversion function registered for layer: NMS_TRT yet.
Converting NMS as custom op: NMS_TRT
WARNING:tensorflow:From /usr/lib/python3.6/dist-packages/uff/converters/tensorflow/converter.py:179: The name tf.AttrValue is deprecated. Please use tf.compat.v1.AttrValue instead.

Warning: No conversion function registered for layer: FlattenConcat_TRT yet.
Converting concat_box_conf as custom op: FlattenConcat_TRT
Warning: No conversion function registered for layer: GridAnchor_TRT yet.
Converting GridAnchor as custom op: GridAnchor_TRT
Warning: No conversion function registered for layer: FlattenConcat_TRT yet.
Converting concat_box_loc as custom op: FlattenConcat_TRT
No. nodes: 450
UFF Output written to tmp.uff
[TensorRT] INFO: UFFParser: parsing Input
[TensorRT] INFO: UFFParser: Applying order forwarding to: Input
...
[TensorRT] INFO: UFFParser: Applying order forwarding to: BoxPredictor_5/Reshape
[TensorRT] INFO: UFFParser: parsing concat_box_loc
[TensorRT] INFO: UFFParser: parsing Squeeze
[TensorRT] INFO: UFFParser: Applying order forwarding to: Squeeze
[TensorRT] INFO: UFFParser: parsing GridAnchor
[libprotobuf FATAL /home/erisuser/p4sw/sw/gpgpu/MachineLearning/DIT/externals/protobuf/aarch64/10.0/include/google/protobuf/repeated_field.h:1408] CHECK failed: (index) < (current_size_): 
Traceback (most recent call last):
  File "main.py", line 41, in <module>
    parser.parse('tmp.uff', network)
RuntimeError: CHECK failed: (index) < (current_size_):
```

The error is a bit cryptic, googling yields a few results but nothing related to TRT or UFF conversion. Any ideas?

From nvidia forum, without any answers.
https://devtalk.nvidia.com/default/topic/1051353/tensorrt/runtimeerror-check-failed-index-lt-current_size_-/
https://devtalk.nvidia.com/default/topic/1046080/tensorrt-support-for-ssd_inception-trained-on-custom-dataset/
https://devtalk.nvidia.com/default/topic/1046895/tensorrt/tensorrt-with-custom-plugin-libprotobuf-fatal-/

**Comment by razekmaiden** [comment]
Same error as @hosaka. I'm using tensorflow==1.13.1 for training and on the nano, and a custom ssd_mobilenet_v2 with 2 output clases.

`WARNING: To create TensorRT plugin nodes, please use the `create_plugin_node` function instead.
NOTE: UFF has been tested with TensorFlow 1.12.0. Other versions are not guaranteed to work
WARNING: The version of TensorFlow installed on this system is not guaranteed to work with UFF.
UFF Version 0.6.3
=== Automatically deduced input nodes ===
[name: "Input"
op: "Placeholder"
input: "Cast"
attr {
  key: "dtype"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "shape"
  value {
    shape {
      dim {
        size: 1
      }
      dim {
        size: 3
      }
      dim {
        size: 300
      }
      dim {
        size: 300
      }
    }
  }
}
]
=========================================

Using output node NMS
Converting to UFF graph
Warning: No conversion function registered for layer: NMS_TRT yet.
Converting NMS as custom op: NMS_TRT
Warning: No conversion function registered for layer: FlattenConcat_TRT yet.
Converting concat_box_conf as custom op: FlattenConcat_TRT
Warning: No conversion function registered for layer: Cast yet.
Converting Cast as custom op: Cast
Warning: No conversion function registered for layer: GridAnchor_TRT yet.
Converting GridAnchor as custom op: GridAnchor_TRT
Warning: No conversion function registered for layer: FlattenConcat_TRT yet.
Converting concat_box_loc as custom op: FlattenConcat_TRT
No. nodes: 644
UFF Output written to tmp.uff
[TensorRT] ERROR: UffParser: Validator error: Cast: Unsupported operation _Cast
[TensorRT] ERROR: Network must have at least one output
Traceback (most recent call last):
  File "main.py", line 43, in <module>
    buf = engine.serialize()
AttributeError: 'NoneType' object has no attribute 'serialize'
`

**Comment by razekmaiden** [comment]
Same error as @hosaka. I'm using tensorflow==1.13.1 for training and on the nano, and a custom ssd_mobilenet_v2 with 2 output clases.

```
WARNING: To create TensorRT plugin nodes, please use the `create_plugin_node` function instead.
NOTE: UFF has been tested with TensorFlow 1.12.0. Other versions are not guaranteed to work
WARNING: The version of TensorFlow installed on this system is not guaranteed to work with UFF.
UFF Version 0.6.3
=== Automatically deduced input nodes ===
[name: "Input"
op: "Placeholder"
input: "Cast"
attr {
  key: "dtype"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "shape"
  value {
    shape {
      dim {
        size: 1
      }
      dim {
        size: 3
      }
      dim {
        size: 300
      }
      dim {
        size: 300
      }
    }
  }
}
]
=========================================

Using output node NMS
Converting to UFF graph
Warning: No conversion function registered for layer: NMS_TRT yet.
Converting NMS as custom op: NMS_TRT
Warning: No conversion function registered for layer: FlattenConcat_TRT yet.
Converting concat_box_conf as custom op: FlattenConcat_TRT
Warning: No conversion function registered for layer: Cast yet.
Converting Cast as custom op: Cast
Warning: No conversion function registered for layer: GridAnchor_TRT yet.
Converting GridAnchor as custom op: GridAnchor_TRT
Warning: No conversion function registered for layer: FlattenConcat_TRT yet.
Converting concat_box_loc as custom op: FlattenConcat_TRT
No. nodes: 644
UFF Output written to tmp.uff
[TensorRT] ERROR: UffParser: Validator error: Cast: Unsupported operation _Cast
[TensorRT] ERROR: Network must have at least one output
Traceback (most recent call last):
  File "main.py", line 43, in <module>
    buf = engine.serialize()
AttributeError: 'NoneType' object has no attribute 'serialize'
```

**Comment by hosaka** [comment]
@razekmaiden I was able to get this working, following the suggestions here, and the next post after that of https://devtalk.nvidia.com/default/topic/1043557/tensorrt/error-uffparser-parser-error-boxpredictor_0-reshape-reshape-1-dimension-specified-more-than-1-/post/5317840/#5317840

I've also joined in on another thread related to this, please see https://github.com/NVIDIA/TensorRT/issues/26

In theory just replacing the ToFloat with Cast should work, but it doesn't for whatever reason.

**Comment by razekmaiden** [comment]
> @razekmaiden I was able to get this working, following the suggestions here, and the next post after that of https://devtalk.nvidia.com/default/topic/1043557/tensorrt/error-uffparser-parser-error-boxpredictor_0-reshape-reshape-1-dimension-specified-more-than-1-/post/5317840/#5317840
> 
> I've also joined in on another thread related to this, please see [NVIDIA/TensorRT#26](https://github.com/NVIDIA/TensorRT/issues/26)
> 
> In theory just replacing the ToFloat with Cast should work, but it doesn't for whatever reason.

Thank's a lot @hosaka I followed the steps and worked for me. I must change the ssd_mobilenet_v2 for a ssd_mobilenet_v1 model. Here is an example of my training process.

[Link](https://colab.research.google.com/drive/1G8Div9FDutujv-Byjr_2-77gI7NLnGfB)

The "optimization" was finally performed on a jetson nano.

**Comment by hosaka** [comment]
@razekmaiden good to hear it worked for you!

You can also drop the `pip install -q pycocotools` from the install, as old models repo checkpoint doesn't use it, as far as I know.

**Comment by mattromlewski** [comment]
> I looked more carefully through the generated frozen graphs with tensorboard and found that ToFloat layer got replaced with the Cast layer during my training, perhaps due to the newer version of TF. I simply replaced ToFloat with Cast in the namespace_plugin_map and 

...

Hello @hosaka, would you be able to share how you replaced ToFloat with Cast in the namespace_plugin_map? Thank you

**Comment by edric1261234** [comment]
> > I looked more carefully through the generated frozen graphs with tensorboard and found that ToFloat layer got replaced with the Cast layer during my training, perhaps due to the newer version of TF. I simply replaced ToFloat with Cast in the namespace_plugin_map and
> 
> ...
> 
> Hello @hosaka, would you be able to share how you replaced ToFloat with Cast in the namespace_plugin_map? Thank you

+1

**Comment by edric1261234** [comment]
And what is the version of your TF, Thank you

**Comment by edric1261234** [comment]
> @razekmaiden I was able to get this working, following the suggestions here, and the next post after that of https://devtalk.nvidia.com/default/topic/1043557/tensorrt/error-uffparser-parser-error-boxpredictor_0-reshape-reshape-1-dimension-specified-more-than-1-/post/5317840/#5317840
> 
> I've also joined in on another thread related to this, please see [NVIDIA/TensorRT#26](https://github.com/NVIDIA/TensorRT/issues/26)
> 
> In theory just replacing the ToFloat with Cast should work, but it doesn't for whatever reason.

What is the version of your TF, Thank you!

**Comment by hosaka** [comment]
@mattromlewski @edric1261234 
Please see my post on another thread https://github.com/NVIDIA/TensorRT/issues/26 and refer to the the nvidia devtalk link as well for more info. I am not sure if this still works, there might have been other improvements, I haven't been following in the past few months.
